## Phase 1

✅ Menu

✅ Orders

✅ Revenue

✅ Branches

✅ Categories

✅ Payment methods

In [86]:
import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta

In [87]:
# create a list of branches

branches = [
    "Manchester Selfridges",
    "London Selfridges",
    "Birmingham Selfridges",
    "Leeds Selfridges"
]

In [88]:
df = pd.read_csv("../data/menu_reference.csv")

In [89]:
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   item_name  30 non-null     object
 1   category   30 non-null     object
 2   price      30 non-null     float64
dtypes: float64(1), object(2)
memory usage: 852.0+ bytes

In [90]:
# create a list of order ids
number_of_orders = 10000
print(number_of_orders)

10000

In [91]:
# create a list of order ids from 1 to number_of_orders and print the first 10 order ids 
order_ids = range(1, number_of_orders + 1)
print(list(order_ids)[:10])

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [92]:
random_branches = random.choices(branches, k=number_of_orders)
print(random_branches[:10])

['Leeds Selfridges', 'London Selfridges', 'Manchester Selfridges', 'Manchester Selfridges', 'London Selfridges', 'London Selfridges', 'Birmingham Selfridges', 'Leeds Selfridges', 'London Selfridges', 'Leeds Selfridges']

In [93]:
random_items = random.choices(df["item_name"], k=number_of_orders)
print(random_items[:10])

['Salmon Nigiri', 'Chicken Yakitori', 'Miso Soup', 'Asahi Beer', 'Chicken Katsu Curry', 'Miso Caramel Brownie', 'Chashu Chicken Ramen', 'Asahi Beer', 'Chicken Yakitori', 'Chocolate Cream Puff']

In [94]:
quantities = np.random.randint(1, 5, size=number_of_orders)
print(quantities[:10])

[1 4 4 2 3 1 2 3 3 2]

In [95]:
price_lookup = dict(zip(df["item_name"], df["price"]))

print(price_lookup)

{'Salmon Nigiri': 5.5, 'Tuna Nigiri': 5.5, 'Salmon Maki': 4.5, 'Crunchy California Roll': 5.5, 'YO! Roll': 6.0, 'Dynamite Roll': 6.5, 'Popcorn Prawn Roll': 6.5, 'Salmon Dragon Roll': 6.5, 'Chicken Katsu Sushi Sando': 7.5, 'Chicken Katsu Curry': 13.5, 'Prawn Katsu Curry': 14.5, 'Beef Teriyaki Donburi': 15.5, 'Chicken Dashi Ramen': 14.5, 'Chashu Chicken Ramen': 14.5, 'Korean Fried Chicken': 7.95, 'Japanese Fried Chicken': 7.95, 'Chicken Gyoza': 7.5, 'Vegetable Gyoza': 6.95, 'Chicken Yakitori': 6.95, 'YO! Fries': 4.95, 'Miso Soup': 3.5, 'Japanese Green Tea': 3.45, 'Coca Cola': 3.95, 'Ramune Soda': 3.95, 'Asahi Beer': 5.95, 'Hakushika Ginjo Sake': 7.5, 'Chocolate Cream Puff': 5.5, 'Miso Caramel Brownie': 5.5, 'Strawberry Little Moons': 5.5, 'Cotton Candy Cheesecake': 6.5}

In [96]:
prices = [price_lookup[item] for item in random_items]

print(prices[:10])

[5.5, 6.95, 3.5, 5.95, 13.5, 5.5, 14.5, 5.95, 6.95, 5.5]

In [97]:
revenues = np.array(prices) * quantities
print(revenues[:10])

[ 5.5  27.8  14.   11.9  40.5   5.5  29.   17.85 20.85 11.  ]

In [98]:
start_date = datetime(2025, 1, 1)
end_date = datetime(2025, 12, 31)

date_range = (end_date - start_date).days

random_dates = [
    (start_date + timedelta(days=random.randint(0, date_range))).date()
    for _ in range(number_of_orders)
]

print(random_dates[:5])

[datetime.date(2025, 9, 1), datetime.date(2025, 6, 8), datetime.date(2025, 9, 30), datetime.date(2025, 6, 11), datetime.date(2025, 7, 29)]

In [99]:
order_hours = np.random.choice(
    [11,12,13,14,15,16,17,18,19,20,21],
    size=number_of_orders,
    p=[0.03,0.12,0.15,0.10,0.05,0.05,0.10,0.15,0.15,0.08,0.02]
)

print(order_hours[:20])

[19 18 18 17 15 13 17 18 17 12 13 18 17 13 16 17 15 12 21 17]

In [100]:
sales_data = pd.DataFrame({
    "order_id": order_ids,
    "branch": random_branches,
    "item_name": random_items,
    "quantity": quantities,
    "price": prices,
    "revenue": revenues,
    "order_date": random_dates,
    "order_hour": order_hours
})

sales_data.head()

,order_id,branch,item_name,quantity,price,revenue,order_date,order_hour
0,1,Leeds Selfridges,Salmon Nigiri,1,5.50,5.5,2025-09-01,19
1,2,London Selfridges,Chicken Yakitori,4,6.95,27.8,2025-06-08,18
2,3,Manchester Selfridges,Miso Soup,4,3.50,14.0,2025-09-30,18
3,4,Manchester Selfridges,Asahi Beer,2,5.95,11.9,2025-06-11,17
4,5,London Selfridges,Chicken Katsu Curry,3,13.50,40.5,2025-07-29,15

In [101]:
category_lookup = dict(zip(df["item_name"], df["category"]))

sales_data["category"] = sales_data["item_name"].map(category_lookup)

sales_data.head()

,order_id,branch,item_name,quantity,price,revenue,order_date,order_hour,category
0,1,Leeds Selfridges,Salmon Nigiri,1,5.50,5.5,2025-09-01,19,Sushi
1,2,London Selfridges,Chicken Yakitori,4,6.95,27.8,2025-06-08,18,Sides
2,3,Manchester Selfridges,Miso Soup,4,3.50,14.0,2025-09-30,18,Drinks
3,4,Manchester Selfridges,Asahi Beer,2,5.95,11.9,2025-06-11,17,Alcohol
4,5,London Selfridges,Chicken Katsu Curry,3,13.50,40.5,2025-07-29,15,Curry

In [102]:
payment_methods = ["Card", "Cash", "Gift Card"]

random_payments = random.choices(
    payment_methods,
    weights=[60, 20, 10],
    k=number_of_orders
)

print(random_payments[:10])

['Card', 'Card', 'Cash', 'Card', 'Cash', 'Card', 'Card', 'Card', 'Card', 'Card']

In [103]:
sales_data["payment_method"] = random_payments

sales_data.head()

,order_id,branch,item_name,quantity,price,revenue,order_date,order_hour,category,payment_method
0,1,Leeds Selfridges,Salmon Nigiri,1,5.50,5.5,2025-09-01,19,Sushi,Card
1,2,London Selfridges,Chicken Yakitori,4,6.95,27.8,2025-06-08,18,Sides,Card
2,3,Manchester Selfridges,Miso Soup,4,3.50,14.0,2025-09-30,18,Drinks,Cash
3,4,Manchester Selfridges,Asahi Beer,2,5.95,11.9,2025-06-11,17,Alcohol,Card
4,5,London Selfridges,Chicken Katsu Curry,3,13.50,40.5,2025-07-29,15,Curry,Cash

## Phase 2

Add business attributes:

# day of week
# month
# weekend flag
# lunch/dinner period

In [104]:
# its making the order_date column a datetime object and creating a new column called day_of_week which contains the day of the week for each order date

sales_data["order_date"] = pd.to_datetime(sales_data["order_date"], errors="coerce")
sales_data["day_of_week"] = sales_data["order_date"].dt.day_name()

sales_data[["order_date", "day_of_week"]].head()

  order_date day_of_week
0 2025-09-01      Monday
1 2025-06-08      Sunday
2 2025-09-30     Tuesday
3 2025-06-11   Wednesday
4 2025-07-29     Tuesday

In [105]:
# create a new column called is_weekend which is True if the day of the week is Saturday or Sunday and False otherwise

sales_data["is_weekend"] = sales_data["day_of_week"].isin(
    ["Saturday", "Sunday"]
)

sales_data[["day_of_week", "is_weekend"]].head(10)

  day_of_week  is_weekend
0      Monday       False
1      Sunday        True
2     Tuesday       False
3   Wednesday       False
4     Tuesday       False
5      Sunday        True
6     Tuesday       False
7    Saturday        True
8   Wednesday       False
9      Monday       False

In [106]:
# create a new column called meal_period which categorizes the order_hour into "Morning", "Lunch", "Dinner", and "Late Night"

def get_meal_period(hour):

    if hour < 12:
        return "Morning"

    elif hour < 17:
        return "Lunch"

    elif hour < 21:
        return "Dinner"

    else:
        return "Late Night"

In [107]:
# apply the get_meal_period function to the order_hour column and create a new column called meal_period

sales_data["meal_period"] = sales_data["order_hour"].apply(get_meal_period)

sales_data[["order_hour", "meal_period"]].head(10)

   order_hour meal_period
0          19      Dinner
1          18      Dinner
2          18      Dinner
3          17      Dinner
4          15       Lunch
5          13       Lunch
6          17      Dinner
7          18      Dinner
8          17      Dinner
9          12       Lunch

In [108]:
# create a new column called order_channel which categorizes the orders into "Dine In", "Takeaway", "Deliveroo", and "Uber Eats" based on the payment method and the branch

order_channels = [
    "Dine In",
    "Takeaway",
    "Deliveroo",
    "Uber Eats"
]

random_channels = random.choices(
    order_channels,
    weights=[50, 15, 20, 15],
    k=number_of_orders
)

print(random_channels[:10])

['Uber Eats', 'Takeaway', 'Takeaway', 'Dine In', 'Uber Eats', 'Deliveroo', 'Deliveroo', 'Uber Eats', 'Dine In', 'Deliveroo']

In [109]:
sales_data["order_channel"] = random_channels

sales_data.head()

,order_id,branch,item_name,quantity,price,revenue,order_date,order_hour,category,payment_method,day_of_week,is_weekend,meal_period,order_channel
0,1,Leeds Selfridges,Salmon Nigiri,1,5.50,5.5,2025-09-01,19,Sushi,Card,Monday,False,Dinner,Uber Eats
1,2,London Selfridges,Chicken Yakitori,4,6.95,27.8,2025-06-08,18,Sides,Card,Sunday,True,Dinner,Takeaway
2,3,Manchester Selfridges,Miso Soup,4,3.50,14.0,2025-09-30,18,Drinks,Cash,Tuesday,False,Dinner,Takeaway
3,4,Manchester Selfridges,Asahi Beer,2,5.95,11.9,2025-06-11,17,Alcohol,Card,Wednesday,False,Dinner,Dine In
4,5,London Selfridges,Chicken Katsu Curry,3,13.50,40.5,2025-07-29,15,Curry,Cash,Tuesday,False,Lunch,Uber Eats

In [110]:
sales_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        10000 non-null  int64
 1   branch          10000 non-null  object
 2   item_name       10000 non-null  object
 3   quantity        10000 non-null  int32
 4   price           10000 non-null  float64
 5   revenue         10000 non-null  float64
 6   order_date      10000 non-null  datetime64[ns]
 7   order_hour      10000 non-null  int32
 8   category        10000 non-null  object
 9   payment_method  10000 non-null  object
 10  day_of_week     10000 non-null  object
 11  is_weekend      10000 non-null  bool
 12  meal_period     10000 non-null  object
 13  order_channel   10000 non-null  object
dtypes: bool(1), datetime64[ns](1), float64(2), int32(2), int64(1), object(7)
memory usage: 947.4+ KB

In [111]:
sales_data.shape

(10000, 14)

In [112]:
sales_data["revenue"].describe().round(2)

count    10000.00
mean        18.25
std         12.24
min          3.45
25%         10.35
50%         15.50
75%         22.50
max         62.00
Name: revenue, dtype: float64

In [113]:
sales_data.to_csv(
    "../data/sales_transactions.csv",
    index=False
)

print("Dataset saved successfully!")

Dataset saved successfully!